config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'groups#index'
  resources :users,  only: [:edit, :update, :index]
  resources :groups, only: [:new, :edit, :create, :update] do
    resources :messages, only: [:index, :create]

    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :users,         through: :group_users
  has_many :group_users
  has_many :messages

  validates :name,        presence: true, uniqueness: true

  def show_last_message
    if (last_message = messages.last).present?
      last_message.content? ? last_message.content : '画像が投稿されています'
    else
      'まだメッセージがありません'
    end
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
  
  mount_uploader :image, ImageUploader
  validates :content_or_image, presence: true

  private
    def content_or_image
      content.presence or image.presence
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages
  has_many :group_users
  has_many :groups,      through: :group_users

end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    group = Group.find(params[:group_id])
    last_message_id = params[:id].to_i
    @messages = group.messages.includes(:user).where("id > #{last_message_id}")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  
  before_action :set_group, only: [:edit, :update]

  def index
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create 
    
    @group = Group.new(group_params)
    @group.users = []
    if @group.save
      # 中間テーブルに値を保存するための追加コード
      @group.user_ids = group_params[:user_ids]
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def update
    if @group.update(group_params)
      redirect_to root_path, notice: 'グループを編集しました'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

  def set_group
    @group = Group.find(params[:id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group,:set_users

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params)
    
    if @message.save
      respond_to do |format|
        format.html{redirect_to group_messages_path(@group), notice: 'メッセージが送信されました'}
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください'
      render :index
    end
  end

  private

  def set_group
    @group = Group.find(params[:group_id])
  end

  def set_users
    @users = User.all
  end

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    # @user = User.new(user_params)
    # if @user.delete
    #   redirect_to destroy_user_session_path, method: :delete, unauthenticated: 'ログインまたは登録が必要です'
    # end
  end

  def index
    return nil if params[:keyword] == ""
    @users = User.where(['name LIKE ?', "%#{params[:keyword]}%"]).where.not(id: current_user.id).limit(10)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path, notice: 'ユーザー情報を更新しました'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:email)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバーを追加"} チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text"}/
      #user-search-result

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right

      #chat-group-users.js-add-user
        .chat-group-user.clearfix.js-chat-member
          %input{name: "group[user_ids][]", type: "hidden", value: current_user.id}
          %p.chat-group-user__name= current_user.name

        - group.users.each do |user|
          - if current_user.name != user.name
            .chat-group-user.clearfix.js-chat-member
              %input{name: "group[user_ids][]", type: "hidden", value: user.id}
              %p.chat-group-user__name
                = user.name 
              %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn
                削除
     
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: {group: @group}

app/views/groups/index.html.haml
.wrapper

  = render 'shared/side_bar'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render 'form',{group: @group}

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key,value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", httpequiv: "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/notifications'
    = yield

app/views/messages/_message.html.haml
.messages__message{data: {id: "#{message.id}"}}
  .uper-message
    .uper-message__name
      = message.user.name
    .uper-message__date
      = message.created_at.in_time_zone('Tokyo').strftime("%Y/%m/%d %H:%M")
      
  .lower-message
    - if message.content.present?
      %p.lower-message__content
        = message.content
    = image_tag message.image, class: 'lower-message__image' if message.image.present?

app/views/messages/index.html.haml
.wrapper
  = render 'shared/side_bar'
  .main
    .main__top
      .main__top--group-name
        = @group.name
      = link_to edit_group_path(@group) do
        %input{type: "submit", value: "Edit", class: "main__top--edit"}
      .member-box
        .member-box__member
          Member :
        .member-box__members
          - @group.users.each do |member|
            = member.name 
            
    .messages{data: {group_id: "#{@group.id}"}}
      = render @messages

    .form
      = form_for [@group, @message] do |f|
        .inputbox
          .inputbox__message
            = f.text_field :content, class: 'inputbox__message--field', placeholder: 'type a message'
            .mask
              = f.label :image, class: 'mask__label' do
                = fa_icon 'picture-o', class: 'icon'
                = f.file_field :image, class: 'mask__label--image'
          = f.submit 'Send', class: 'sendmessage'

app/views/shared/_error_messages.html.haml
- if resource.errors.any?
  #error_explanation
    %h2
      = I18n.t("errors.messages.not_saved",                 |
        count: resource.errors.count,                       |
        resource: resource.class.model_name.human.downcase) |
    %ul
      - resource.errors.full_messages.each do |message|
        %li= message

app/views/shared/_side_bar.html.haml
.group
  .group__top
    .group__top__box 
      .group__top__box--name
        = current_user.name
      .group__top__box--icon
        = link_to '/groups/new' do
          = fa_icon 'pencil-square-o', class: "group__top--icon"
        = link_to edit_user_path(current_user), 'data-turbolinks': false do
          = fa_icon 'cog', class: "group__top--icon"
  .group-footer
    - current_user.groups.order(created_at: :DESC).each do |group|
      .group-footer__list
        = link_to "/groups/#{group.id}/messages", 'data-turbolinks': false do
          .group-footer__list--title
            = group.name
          .group-footer__list--text
            = group.show_last_message

app/views/shared/edit.html.haml
%h2 Change your password
= form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :put }) do |f|
  = render "devise/shared/error_messages", resource: resource
  = f.hidden_field :reset_password_token
  .field
    = f.label :password, "New password"
    %br/
    - if @minimum_password_length
      %em
        (#{@minimum_password_length} characters minimum)
      %br/
    = f.password_field :password, autofocus: true, autocomplete: "new-password"
  .field
    = f.label :password_confirmation, "Confirm new password"
    %br/
    = f.password_field :password_confirmation, autocomplete: "new-password"
  .actions
    = f.submit "Change my password"
= render "devise/shared/links"

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'